---
- hosts: all
  sudo: yes
  remote_user: vagrant
  tasks:
    - name: Update apt
      apt: update_cache=yes

    - name: Install pip3 to python3
      apt: pkg=python3-pip state=present

    - name: Install Git to clone my repository
      apt: pkg=git state=present

    - name: Clone my repository
      git: repo=https://github.com/ainokila/ProyectoIV dest=/home/vagrant/cve

    - name: Install requirements
      command: pip3 install -r /home/vagrant/cve/requirements.txt